/*jshint node:true*/
/**
 * Generated by Maverick CLI
 */
module.exports = function (app) {
    var express = require('express');
    var maverickRouter = express.Router();
    var shell = require('shelljs');

    maverickRouter.get('/', function (req, res) {
        //shell.exec("ember g maverick-builder");
        res.send({ project: { id: 1, number: 123, name: 'Fooshnickins' } });
    });
    
    maverickRouter.get('/update-ember', function (req, res) {
        var cmd = shell.exec("ember g update-ember");
        res.send(cmd);
    });
    
    maverickRouter.get('/action/:step', function (req, res) {
        var params = req.params;
        var cmd = shell.exec("ember g "+params.step+"");
        res.send(cmd);
    });
    
    maverickRouter.get('/maverick-file-check/:step', function (req, res) {
        var params = req.params;
        var cmd = shell.exec("ember g maverick-file-check "+params.step);
        res.send(cmd);
    });
    
    maverickRouter.get('/check/:step', function (req, res) {
        var params = req.params;
        var cmd = shell.exec("ember g "+params.step+"-check");
        res.send(cmd);
    });

    maverickRouter.get('/:id', function (req, res) {
        res.send({
            'maverick': {
                id: req.params.id
            }
        });
    });

    // The POST and PUT call will not contain a request body
    // because the body-parser is not included by default.
    // To use req.body, run:

    //    npm install --save-dev body-parser

    // After installing, you need to `use` the body-parser for
    // this mock uncommenting the following line:
    //
    //app.use('/api/maverick', require('body-parser'));
    app.use('/api/maverick', maverickRouter);
};
